# Generated by Django 4.2.20 on 2025-04-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('issue', models.CharField(choices=[('Headache', 'Headache'), ('Fever', 'Fever'), ('Migraine', 'Migraine'), ('Other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treated', models.BooleanField(default=False)),
            ],
        ),
    ]
